### PR TITLE
Create Yeoman generator for OpenMRS ESMs

### PR DESCRIPTION
**Pull request by brandones**
This is a first pass at a working Yeoman generator for OpenMRS ESMs.

Wishlist for future work:
- more inline documentation about what each file does
- choose whether or not to include routing with a flag
- a generator or a variation on this generator for dashboard widgets
- additional optional boilerplate that demonstrates how to use esm-api and esm-error-boundary

### CODE REVIEW

**Comment by brandones** [comment]
See https://github.com/brandones/generator-openmrs-test for sample output.

Yeoman interface:
Screenshot from 2020-03-24 14-37-22

Loaded in the browser:
Screenshot from 2020-03-24 13-53-07

**Comment by joeldenning** [comment]
Hey Brandon - i got a jira notification about this and took a look. Are you aware of https://github.com/single-spa/create-single-spa?

I recently launched it as part of single-spa@5. I intentionally created it with extensibility in mind, even thinking of OpenMRS as a potential user of it. Have you considered reusing the generators in there? I think the benefit of doing so would be inheriting a bunch of downstream bug fixes and beat practices that dozens of organizations outside of OpenMRS are contributing to.

If interested, the main extensibility concept I’m hoping will work out for OpenMRS is [composing generators](https://yeoman.io/authoring/composability.html). My thought is that options could be passed into create-single-spa which modify its behavior.

If you have interest in approaching things that way, I’d be happy to collaborate on it

**Comment by brandones** [comment]
Hi Joel! I wasn't aware of it, and so hadn't considered it, but it sounds like the right approach. It looks like that might also give us generators for Angular and Vue relatively easily, which would be very cool.

This generator as written composes generator-node. I'm glad to hear you created yours with extensibility in mind, because I've had to do some unpleasant hacking around generator-node (and, as an aside, at the end I've realized that I gained almost nothing by using generator-node... but hey, this was my first generator, and I learned a lot).

Should I just take a crack at it and see if I can make a generator-openmrs that `compose`s`With` generator-single-spa? Or is there somewhere else I should begin?

**Comment by joeldenning** [comment]
Here's how I think I'd approach an openmrs-specific tool:

1. I think `npm init openmrs` is the easiest api for people to use. This means there needs to be an npm project called `create-openmrs` that has a [`bin` field](https://github.com/single-spa/create-single-spa/blob/cf26d3aa77a4262c4535bc4f217dc6e1614e59e1/packages/create-single-spa/package.json#L6).
1. A successful openmrs-specific generator would likely include creating somewhere around 5ish npm packages. I think that [a lerna monorepo](https://lerna.js.org/) worked very well for create-single-spa, and could make local development and overall project management of all those create-openmrs packages easier. Monorepos are sort of the opposite of microfrontends 😄, but I think they work very well for this case of managing many npm packages together.
1. I think the following npm packages would likely be need to be implemented:
  a) `webpack-config-openmrs-single-spa` (would extend [webpack-config-single-spa](https://github.com/single-spa/create-single-spa/tree/master/packages/webpack-config-single-spa) with openmrs-specific stuff (such as translation stuff, openmrs-specific webpack externals, etc)
  b) `webpack-config-openmrs-single-spa-react` (would extend [webpack-config-single-spa-react](https://github.com/single-spa/create-single-spa/tree/master/packages/webpack-config-single-spa-react)).
  c) `generator-openmrs`. This would would call `this.composeWith(require.resolve('generator-single-spa/src/generator-single-spa.js')`, passing in openmrs-specific options that are used instead of prompting the user for things. This part is where we'd have to dig in to find out exactly which parts can be composed and which can't
  d) `openmrs-tsconfig`. This would be an [extendable typescript config file](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#configuration-inheritance-with-extends). The generator-openmrs project would have a `tsconfig.json` template in it that would extend the typescript config but still allow for project-specific customization
  e) `openmrs-jest-config` - this would be a shareable jest config. Used like so:
```ts
// jest.config.js
const config = require('openmrs-jest-config');

config.moduleNameMapper['custom-mocked-file'] = '<rootDir>/__mocks__/custom-mocked-file.ts'

module.exports = config
```

Using the lerna monorepo strategy would mean that there would be only one github repository, create-openmrs, with the following directory structure:

```
packages/
  create-openmrs/
  generator-openmrs/
  webpack-config-openmrs-single-spa/
  webpack-config-openmrs-single-spa-react/
  openmrs-ts-config/
  openmrs-jest-config/
```

**Comment by brandones** [comment]
Awesome, thanks so much for the guidance. I'm leaving the branch here in case anyone wants to use the existing generator before I have the chance to reimplement.

**Comment by joeldenning** [comment]
👍 I’m happy to review some of the early PRs as you get going on it, if you’d like

**Comment by brandones** [comment]
@joeldenning What's the easiest way for me to ping you about new PRs? Or are you watching this repo? First one's here: https://github.com/openmrs/openmrs-frontend-generators/pull/2

**Comment by brandones** [comment]
Also, what's the best venue to chat about generator-single-spa extensibility? I have thoughts

**Comment by brandones** [comment]
Here's what I think are the differences the openmrs generator should have with respect to the single-spa generator (once the single-spa generator has TS support (let me know if you'd like support on adding that feature)):

#### Easy changes
- more deps in package.json: we'll programmatically install-save them in the generator
- webpack should come with style-loader set up and with the externals: this will be part of `webpack-config-openmrs-single-spa`
- the addition of a couple more boilerplate config files

#### Less easy changes
- adding to the entrypoint file
    - the `export { backendDependencies } ...` line
    - the `export const importTranslation = ...` lines

Though actually, these could just be concatenated onto the file that generator-single-spa produces. Maybe that would be the best way about it.

- adding to root.component.tsx
    - wrapping the component in react-root-decorator (which requires an import at the top)
    - more optionally: config schema definition above the component definition
    - and: a use of `config.useSchema` within the component definition
    - also nice to have: an example usage of i18next
    - also nice to have someday: an example usage of error-boundary

Perhaps this is the one thing that might warrant making changes to generator-single-spa to make it more extensible (presumably by adding `option`s, which seem to be pretty much the only "API" that Yeoman generators have).

#### Questions

- Should we include the standard mocks for esm-api, esm-error-handling, and esm-module-config ? Should we manage those mocks in an independent package, so that they can be kept in sync with the ESMs that they mock?
- We can probably just use the .tsconfig from generator-single-spa out of the box, no?

**Comment by joeldenning** [comment]
> What's the easiest way for me to ping you about new PRs? Or are you watching this repo?

I just watched this repo. I zero inbox my github notifications almost daily, so I'll add any notifications from here to that daily queue.

> Also, what's the best venue to chat about generator-single-spa extensibility? I have thoughts

single-spa slack or openmrs slack. I'm still in both

Regarding your third comment, I'll respond to the questions there when I get a chance.

**Comment by joeldenning** [comment]
> adding to the entrypoint file 

The other difference is that the file is a `.tsx` instead of `.js`. Right now create-single-spa doesn't yet support typescript, but it will soon (https://github.com/single-spa/create-single-spa/issues/38).

Adding to the end of the file might work, but seems fairly brittle. I think OpenMRS could just maintain its own entrypoint file that has the translation stuff and backend dependencies.

Same goes for root.component.js - it's such a small file that I don't think it's crucial to reuse it between openmrs and create-single-spa

> Should we include the standard mocks for esm-api, esm-error-handling, and esm-module-config ? Should we manage those mocks in an independent package, so that they can be kept in sync with the ESMs that they mock?

Yes, I think this is a good idea. Especially if it's possible for individual projects to override the mocks if needed. I think putting the mocks into an `openmrs-jest-config` package (along with a jest config) would be good.

> We can probably just use the .tsconfig from generator-single-spa out of the box, no?

generator single-spa doesn't have a tsconfig yet. But when it does, I agree it would probably be sufficient for openmrs' needs. In fact, I'd be willing just to take [the openmrs tsconfig](https://github.com/openmrs/openmrs-esm-patient-chart-widgets/blob/master/tsconfig.json) wholesale.

**Pull request closed without merging**
